### ISSUE TITLE
IgDetective YAML error and absence of license

### ISSUE THREAD

**Issue by DorianCoding** [applied-phylo-lab/CloseRead_ig-assembly-eval#1]
Hello,

Your IgDetective yaml seems incorrect and verification fails as version does not match. On a classic x64 linux machine with python 3.12, you should see the errors.

For example: 
```yaml
ncurses=6.4=hcb278e6_0
```

does not seem to exist but [linux-64/ncurses-6.4-h6a678d5_0](https://anaconda.org/anaconda/ncurses/files). There is also the same issue for other dependancies of this file.

Secondly you lack a license on your repo, would you mind to provide one? https://choosealicense.com/no-permission/

Thanks.

**Comment by zhuyixin43** [comment]
Hello @DorianCoding ,

Thank you for bringing these issues to my attention!

**Regarding your first question**: It seems the YAML file had unnecessary build strings—apologies for the oversight! I’ve removed them and updated the file. I also specified in the YAML file that Python 3.10 will be installed and used for the analysis, so ideally, Python 3.12 should not be used for downstream tasks. The changes are included in the latest commit ([main 3e40ba7]). Could you try again and let me know if you encounter any further issues?

**Regarding your second question**: Thank you for pointing this out as well! I’ve now added a license to the repository.

Best regards.

**Comment by DorianCoding** [comment]
Hello and thanks for the license and your quick answer.

> It seems the YAML file had unnecessary build strings—apologies for the oversight! I’ve removed them and updated the file

I'II give a look tomorrow but it seems you've changed both YAML and you've given the same name? Is it expected? Do I need to change the prefix?

**Comment by zhuyixin43** [comment]
Hi!

Nice catch, sorry it was not intended - I copied the wrong file. Please see commit [main ce2b471] for the corrected version and you shouldn't need to change anything. Let me know if you encounter any further issues.

**Comment by DorianCoding** [comment]
Okay thanks. I'm creating another issue to describe what I've encountered.
